[package]
name = "j-check"
version = "0.1.0"
edition = "2024"

[dependencies]
jj-lib = ">=0.8.0"
# TODO: Add git checks
git2 = { version = "0.20.1", features = ["vendored-libgit2"] }
serde_json = "1.0"
