[package]
name = "jj-check"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = ">=4.5.40"
jj-lib = ">=0.30.0"
jj-cli = { version = ">=0.30.0", default-features = false, features = ["git", ] }
serde_json = ">=1.0"
